FROM php:8.2-apache

COPY . /RonDockeerproject/scr/

WORKDIR /RonDockeerproject/scr/

RUN docker-php-ext-install mysqli pdo pdo_mysql && docker-php-ext-enable mysqli pdo_mysql

EXPOSE 80
EXPOSE 443

CMD [ "apache2-foreground" ]
